### ISSUE TITLE
Menu-bar-page

### ISSUE THREAD

**Issue by Hadeelalhaj** [Hadeelalhaj/Hadeelalhaj.github.io#2]
in this page :
1- I am not sure if i have to add the "X" icon since it's a transition from the first page.
2- i can't position my large gray word "in line 18" WEB to be aligned exactly to the edge of my view port

**Comment by gorazd** [comment]
What page?

**Comment by gorazd** [comment]
This page: https://hadeelalhaj.github.io/menu-bar.html, it helps if you give me the link to code/page that is giving you the issue.

1. Menu should not be a separate page but an element inside every page, refer to the exercise from friday: 
https://github.com/gorazd/css-exercises/tree/master/js-hamburger
2. Try moving your word by adding another transform:
`transform: rotate(90deg) translateX(360px);`
