### ISSUE TITLE
scale issue " size doesn't match " 

### ISSUE THREAD

**Issue by Hadeelalhaj** [Hadeelalhaj/Hadeelalhaj.github.io#3]
Hi!
I am having some issues with the scale " in my xd i have in this page all the elements fits the same page and i am applying the same font size and images size but i still feel that it's so huge and they don't match the real design. 
https://github.com/Hadeelalhaj/Hadeelalhaj.github.io/blob/master/projects.html

**Comment by gorazd** [comment]
Hello, could you please send me your XD file?

Or upload it to the Drive.
