### ISSUE TITLE
Changing typeface for document

### ISSUE THREAD

**Issue by Hadeelalhaj** [Hadeelalhaj/Hadeelalhaj.github.io#4]
Hi! 
I would like to change my font family to "gotham " is it possible? and if yes how can i do it ?
https://github.com/Hadeelalhaj/Hadeelalhaj.github.io/blob/master/index.html

Thanks

**Comment by Hadeelalhaj** [comment]
Hi! 
yes it's in the repository, i added " video " and " Xd"

Thank you

**Comment by gorazd** [comment]
Hello, I am unable to see it. Did you push it to the repository?

**Comment by Hadeelalhaj** [comment]
Hi!
Yes I pushed it again.
incase it's not working you can find it on :
https://drive.google.com/drive/u/1/folders/15M0s86CkkXxu-AW5IzwQm77LteMMYgyw
Thank you.

**Comment by gorazd** [comment]
Ciao Hadeel,
you will need to use @font-face to include your font:
https://css-tricks.com/snippets/css/using-font-face/

Before that you need to convert your .otf fonts to woff2 and woff, you can do that here:
https://transfonter.org/

Now the question, do you own the Gotham family and have a web licence?
